version: '2'

services:
  php:
    build: ./images/php
    container_name: ${PROJECT}php
    ports:
      - '127.0.0.1:9000:9000'
    networks:
      - bitrix
    volumes_from:
      - files
    depends_on:
      - files
    environment: 
      - SITE_DOMAIN=${SITE_DOMAIN}

  web.local:
    build: ./images/nginx
    container_name: ${PROJECT}web
    networks:
      - bitrix
    links:
      - php
    restart: always
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    volumes_from:
      - files
    depends_on:
      - files
    environment: 
      - SITE_DOMAIN=${SITE_DOMAIN}

  db:
    build: ./images/mysql
    container_name: ${PROJECT}db
    networks:
      - bitrix
    restart: always
    ports:
      - 3306:3306
    volumes_from:
      - files
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: bitrixpwd
      MYSQL_ROOT_PASSWORD: rootpwd

  adminer:
    image: adminer
    container_name: ${PROJECT}adminer
    networks:
      - bitrix
    links:
      - db:db
    restart: always
    ports:
      - 8080:8080
    environment:
      UPLOAD: 1024M

  memcached:
    image: memcached:alpine
    restart: always
    container_name: ${PROJECT}memcached
    command: 
      - "--memory-limit=512"
    volumes_from:
      - files
    ports:
      - 11211:11211
    networks:
      - bitrix

  files:
    image: alpine:latest
    container_name: ${PROJECT}files
    volumes:
      - ./../logs/nginx:/var/log/nginx
      - ./../logs/php:/var/log/php
      - ./../logs/mysql:/var/log/mysql
      - ./../logs/memcached:/var/log/memcached
      - ./../cache:/var/lib/memcached
      - ./../public:/var/www/bitrix
      - ${UPLOAD_FOLDER}:/var/www/bitrix/upload
      - ./../db:/var/lib/mysql
    networks:
      - bitrix

networks:
  bitrix:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.150.0.0/24