version: '3'

services: 

  db:
    build: ../../images/bitrix-mysql/5.7
    restart: always
    volumes: 
      - ${DB_FOLDER_HOST}:${DB_FOLDER_CONTAINER}
      - ${EXCHANGE_FOLDER_HOST}:${EXCHANGE_FOLDER_CONTAINER}

  bitrix:
    build:
      context: ../../images/bitrix-php/7.1
      args: 
        BX_SERVER_NAME: ${BITRIX_SERVER_NAME}
    hostname: ${BITRIX_SERVER_NAME}
    restart: always
    links:
      - db:database
    depends_on:
      - db
    volumes: 
      - ${BITRIX_WWW_HOST}:${BITRIX_WWW_CONTAINER}
    ports:
      - ${BITRIX_PORT_HOST}:${BITRIX_PORT_CONTAINER}
      - ${BITRIX_PORT_SSL_HOST}:${BITRIX_PORT_SSL_CONTAINER}

  adminer:
    image: adminer
    restart: always
    links:
      - db:database
    ports:
      - ${ADMINER_PORT_HOST}:8080
    
