version: '2'

services:
  web.local:
    build: ../../images/php-apache
    container_name: ${PROJECT}web
    networks:
      - bitrix
    restart: always
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    volumes_from:
      - files
    depends_on:
      - files
    environment: 
      - SITE_DOMAIN=${SITE_DOMAIN}

  db:
    build: ../../images/mariadb
    container_name: ${PROJECT}db
    networks:
      - bitrix
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes_from:
      - files
    environment:
      MYSQL_DATABASE: ${HOSTING_USER}
      MYSQL_USER: ${HOSTING_USER}
      MYSQL_PASSWORD: ${HOSTING_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}

  adminer:
    image: adminer
    container_name: ${PROJECT}adminer
    networks:
      - bitrix
    links:
      - db:db
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      UPLOAD: 1024M

  files:
    image: alpine:latest
    container_name: ${PROJECT}files
    volumes:
      - ${DATA_PATH}/public:/var/www/bitrix
      - ${UPLOAD_PATH}:/var/www/bitrix/upload
      - ${DATA_PATH}/db:/var/lib/mysql
    networks:
      - bitrix

networks:
  bitrix:
    driver: bridge